version: '3.8'

services:
  mysql:
    image: mysql:latest
    container_name: mysql
    restart: unless-stopped
    environment:
      MYSQL_DATABASE: kaddem
      MYSQL_ROOT_PASSWORD:
    ports:
      - "3306:3306"
    volumes:
      - mysql-data:/var/lib/mysql

  spring-boot-app:
    image: mohamedoussemaboussida/kaddem:1.0.0
    container_name: spring-boot-app
    restart: on-failure
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://localhost:3306/kaddem?&createDatabaseIfNotExist=true
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD:
      SPRING_JPA_SHOW_SQL: "true"
    ports:
      - "8082:8082"
    depends_on:
      - mysql
    tty: true
    stdin_open: true

volumes:
  mysql-data:

